[package]
name = "entity_selection"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
hexx = { workspace = true }

# internal dependencies
common = { workspace = true }
camera = { workspace = true }