[package]
name = "pathfinding"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
hexx = { workspace = true }

# internal dependencies
common = { workspace = true }

[dev-dependencies]
universe_builder = { workspace = true }
test_utils = { workspace = true }