[package]
name = "test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
common = { workspace = true }
universe_builder = { workspace = true }
universe_loader = { workspace = true }