[package]
name = "bevy_space"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["trace"] }
bevy_egui = "0.28.0"
hexx = "0.17.0"
iyes_perf_ui = "0.3.0"
rand = "0.8.5"

[patch.crates-io]
hexx = { git = "https://github.com/ManevilleF/hexx.git", branch = "feat/bevy_0.14" }
