[package]
name = "bevy_space"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0-rc.4", features = ["trace"] }
bevy_egui = { git = "https://github.com/Friz64/bevy_egui.git", branch = "bevy-0.14" }
hexx = "0.17.0"
iyes_perf_ui = { git = "https://github.com/kristoff3r/iyes_perf_ui" }
