[package]
name = "bevy_space"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", features = ["trace"] }
bevy_egui = "0.32.0"
hexx = { version = "0.20.0", features = ["serde"] }
iyes_perf_ui = "0.4.0"
image = "0.25.5"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
leafwing_manifest = { version = "0.3.0", features = [] }
paste = "1.0.15"

[dev-dependencies]
rstest = "0.24.0"

[patch.crates-io]
iyes_perf_ui = { git = "https://github.com/Affinator/iyes_perf_ui.git", rev = "cec8ff80a33dae570eb9af59b60b5c298e192f80" }
