[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"

# internal dependencies
common = { workspace = true }
entity_spawners = { workspace = true }
pathfinding = { workspace = true }

[dev-dependencies]
test_utils = { workspace = true }